version: '3.3'
services:
  ct-trading-gateway:
    container_name: ct-trading-gateway
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
      - 3080:3080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
